# Generated by Django 3.0.6 on 2020-08-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0004_auto_20200809_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermark',
            old_name='originalimage',
            new_name='src',
        ),
    ]
