# Generated by Django 3.1.3 on 2020-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0008_auto_20201113_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markimage',
            name='hpos_rel',
        ),
        migrations.RemoveField(
            model_name='markimage',
            name='vpos_rel',
        ),
    ]
