# Generated by Django 3.1.3 on 2020-11-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0009_auto_20201113_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markimage',
            name='halgin',
        ),
        migrations.RemoveField(
            model_name='markimage',
            name='valgin',
        ),
        migrations.AddField(
            model_name='markimage',
            name='halign',
            field=models.CharField(choices=[('LF', 'left'), ('CT', 'center'), ('RT', 'right')], default='LF', help_text='position of the watermark', max_length=2, verbose_name='horizontal alignment'),
        ),
        migrations.AddField(
            model_name='markimage',
            name='valign',
            field=models.CharField(choices=[('TP', 'top'), ('CT', 'center'), ('BT', 'bottom')], default='TP', help_text='position of the watermark', max_length=2, verbose_name='vertical alignment'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='border',
            field=models.DecimalField(decimal_places=0, default=25, help_text='Border in the image. Default is 25.', max_digits=3, verbose_name='border'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='proportion',
            field=models.DecimalField(decimal_places=0, default=5, help_text='Change propotion between image and watermark. Default is 5.', max_digits=3, verbose_name='proportion'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='src',
            field=models.ImageField(help_text='Select image what should be watermarked.', upload_to='wm/org', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='wm',
            field=models.ForeignKey(help_text='Embedded watermark inside the image.', on_delete=django.db.models.deletion.RESTRICT, to='watermark.watermark', verbose_name='watermark'),
        ),
    ]
