# Generated by Django 3.1.3 on 2020-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0011_auto_20201113_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markimage',
            name='proportion',
            field=models.DecimalField(decimal_places=0, default=5, help_text='Propotion between image and watermark. Default is 5.', max_digits=3, verbose_name='proportion'),
        ),
    ]
