# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: PrivateRegistry
    command: login

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: PrivateRegistry
    repository: firemark
    command: buildAndPush
    tags: latest