# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: $(dockerHub)
    command: login

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: $(dockerHub)
    repository: jensb91/www
    command: buildAndPush
    tags: latest