# Generated by Django 3.0.6 on 2020-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0002_auto_20200809_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='markimage',
            name='border',
            field=models.DecimalField(decimal_places=0, default=25, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markimage',
            name='proportion',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=3),
            preserve_default=False,
        ),
    ]
