# Generated by Django 3.0.6 on 2020-08-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0005_auto_20200809_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='markimage',
            name='wm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watermark.Watermark'),
            preserve_default=False,
        ),
    ]
