# Generated by Django 3.0.6 on 2020-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0006_markimage_wm'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermark',
            name='name',
            field=models.CharField(default='NoName', max_length=40),
            preserve_default=False,
        ),
    ]
