# Generated by Django 3.1.3 on 2020-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0007_watermark_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='markimage',
            name='halgin',
            field=models.CharField(choices=[('LF', 'left'), ('CT', 'center'), ('RT', 'right')], default='LF', max_length=2),
        ),
        migrations.AddField(
            model_name='markimage',
            name='valgin',
            field=models.CharField(choices=[('TP', 'top'), ('CT', 'center'), ('BT', 'bottom')], default='TP', max_length=2),
        ),
    ]
