# Generated by Django 3.1.3 on 2020-11-13 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0010_auto_20201113_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markimage',
            old_name='modified',
            new_name='modifiy_time',
        ),
        migrations.RemoveField(
            model_name='markimage',
            name='created',
        ),
        migrations.AddField(
            model_name='markimage',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='upload time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markimage',
            name='src',
            field=models.ImageField(help_text='Select image which should be watermarked.', upload_to='wm/org', verbose_name='Image'),
        ),
    ]
