# Generated by Django 3.1.3 on 2020-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0012_auto_20201113_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markimage',
            name='halign',
            field=models.CharField(choices=[('LF', 'left'), ('CT', 'center'), ('RT', 'right')], default='RT', help_text='position of the watermark', max_length=2, verbose_name='horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='markimage',
            name='valign',
            field=models.CharField(choices=[('TP', 'top'), ('CT', 'center'), ('BT', 'bottom')], default='BT', help_text='position of the watermark', max_length=2, verbose_name='vertical alignment'),
        ),
    ]
