# Generated by Django 5.0.4 on 2024-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0013_auto_20201127_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markimage',
            options={'verbose_name': 'markedimage', 'verbose_name_plural': 'markedimages'},
        ),
        migrations.AlterModelOptions(
            name='watermark',
            options={'verbose_name': 'watermark', 'verbose_name_plural': 'watermarks'},
        ),
        migrations.AlterField(
            model_name='markimage',
            name='src',
            field=models.ImageField(help_text='Select image which should be watermarked.', upload_to='images/org', verbose_name='Image'),
        ),
    ]
