# Generated by Django 5.0.4 on 2024-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0014_alter_markimage_options_alter_watermark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='src',
            field=models.ImageField(upload_to='watermarks'),
        ),
    ]
