name: FTP Deployment

on:
  push:
    branches:
      - ci/deploytest
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install python requirements
        working-directory: backend
        run: python -m pip install -r requirements.txt
      - name: Create static files
        working-directory: backend
        run: python manage.py collectstatic
      - name: Copy static files into httpdocs dir
        run: cp -r -v ./backend/static ./httpdocs/static
      - name: Create / touch restart.txt for passenger restart
        run: |
          mkdir backend/tmp
          touch backend/tmp/restart.txt
      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./
          dry-run: false